name: Build Done

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dry_run:
        required: true
        type: boolean

jobs:
  done:
    runs-on: ubuntu-latest
    steps:
      - name: Print done info
        run: |
          echo "Finished build and publish ${{ inputs.version }}"
          echo "Docker Image: https://hub.docker.com/r/willowgod/artalk/tags"
          echo "GitHub Release: https://github.com/${{ github.repository }}/releases/tag/${{ inputs.version }}"
