name: Release
run-name: Release ${{ inputs.version }} ${{ inputs.dry_run && '(Dry-Run)' || '' }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version, e.g. v1.0.0"
        type: string
        required: true
      dry_run:
        description: "Dry run"
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ inputs.version }}
      dry_run: ${{ inputs.dry_run || false }}
    secrets: inherit
